export type VolunteerFormData = {
  id?: string;
  title: string;
  name: string;
  startAddress: string;
  startLat: number;
  startLng: number;
  arriveAddress: string;
  arriveLat: number;
  arriveLng: number;
  gender: string;
  age: number;
  weight: number;
  image: string;
  desc: string;
  petDesc: string;
  requesterName: string;
  requesterPhone: string;
  requesterInfo: string;
  createdAt: Date;
};